# Generated by Django 2.2.3 on 2020-06-24 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(blank=True, default='', help_text='HTML')),
                ('timestamp', models.DateField(db_index=True)),
                ('is_show', models.BooleanField(db_index=True, default=False)),
                ('link', models.URLField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_post',
            },
        ),
    ]
