# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table              = "terraform-locks-982947632035"
    encrypt                     = true
    key                         = "aws-data/terraform.tfstate"
    region                      = "us-east-2"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    bucket                      = "terraform-states-982947632035"
  }
}
